---
title: <span style="color:#034a94"> **Código R - Predicción**</span>
author: "Métodos y Simulación Estadística"
output: html_document
css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment =NA )
```


</br></br>

### <span style="color:#FF7F00">**Ejemplo**</span> 

</br>


Para el modelo $\text{bio_total} = \beta_{0} + \beta_{1} \hspace{.3cm} \text{diametro} + \varepsilon$

</br>

```{r}
library(paqueteMET)
data(biomasa)
modelo1=lm(bio_total ~ diametro, data=biomasa)
summary(modelo1)
```

</br></br>

### **Intervalos de confianza del 95%**

```{r}
confint(modelo1)
```

</br></br>

### **Inferencia sobre los parámetros**

```{r}
confint(object = modelo1, parm="diametro", level = 0.95)
```

</br></br>

### **Predicción de $E[Y|x_{o}]$**

```{r}
predict(modelo1, data.frame(diametro=20), interval = "confidence", level = 0.95)
```

</br></br>

### **Predicción de  $Y_{0}$**


```{r}
predict(modelo1, data.frame(diametro=20), interval = "prediction", level = 0.95)
```
