---
title: "Código R - correlación"
author: "dgonzalez"
date: "2023-03-10"
output: html_document
---
---
title: <span style="color:#034a94"> **Análisis de correlación**</span>
author: "Métodos y Simulación Estadística"
output: html_document
css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)

c1="#FF7F00"
c2="#FEB0C6"
c3="#034A94"
c4="#686868"
#-------------------------------------------------------------------------
library(tidyverse)
# install.packages("PerformanceAnalytics")
library(PerformanceAnalytics)


#install.packages("devtools") # solo una vez
# devtools::install_github("dgonxalex80/paqueteMET") # descarga paqueteDEG
library(paqueteMET) # activa paqueteMET
data("biomasa") # carga la base biomasa

gen.corr.data<- function(rho,n){
x <- rnorm(n)
z <- rnorm(n)
y<- rho*x + sqrt(1-rho^2)*z
result <-cbind(y,x)
return(result)
}
#-------------------------------------------------------------------------
library(ggplot2)
library(patchwork)
Theme1= theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12))
#------------------------------------------------------------------------
Theme2= theme(
        #axis.text.x = element_blank(),
        #axis.text.y = element_blank(),
        #axis.ticks = element_blank(),
        axis.title.x = element_text(size = 11),
        axis.title.y = element_text(size = 11))

data(biomasa)
biomasa38=biomasa[,3:8]
#------------------------------------------------------------------------
# Fijamos semilla
set.seed(20)
# Generamos datos aleatorios para la variable X
X <- sample(c("Si", "No"), 100, replace = TRUE)
# "No" "Si" "Si" "No"  "No" "Si" "No" "Si" "No" "No"

# Generamos datos aleatorios para la variable Y
Y <- sample(c("Europa", "America", "Africa"), 100, replace = TRUE)
# "Europa" "Africa"  "Africa"  "Europa"  "Africa" 
# "Europa" "Europa"  "Europa"  "America" "America"

tabla <- table(X, Y)



```

</br></br></br>

#### **Matriz de correlaciones**

```{r}
library(paqueteMET)
data(biomasa) # data contenida en  paqueteMET
head(biomasa) # primeros 6 registros de la data
cor(biomasa[,3:8]) %>%  # matriz de correlaciones 
  round(.,3      )

```


</br></br></br>

### **Matriz de correlaciones - otra alternativa**

</br>

```{r, message=FALSE, warning=FALSE}
library(GGally)
ggpairs(biomasa[,5:8], title="Biomasa") 
```


</br></br></br>



#### **Visualización tabla de contingencia**

</br>

```{r}
library(tidyverse)
tabla = c(80,9,30,21) %>% 
           matrix(., nrow = 2) 
colnames(tabla)=c("Africa", "America")
rownames(tabla)=c("si", "no")


mosaicplot(tabla, cex = 1.1, col = c(c1,c3,c4), main = "Proyectos aprobados sistema alimentario")

```

Fuente : Ejemplo simulado para fines académicos

</br></br>

### **Coeficiente Phi**

</br>

```{r}
library(DescTools)
cat("Coeficiente Phi         :", Phi(tabla), "\n")
```


</br></br>

### **Coeficiente V de Cramer**

</br>

```{r, eval=FALSE}

# install.packages("DescTools")
library(DescTools)
cat("Coeficiente V de Cramer :", CramerV(tabla)) 
```


